name: daneshjouyar_test
# Countries Explorer App — Clean Architecture, BLoC (Cubit), Dio, GoRouter, M3, L10n
description: >-
  Countries Explorer showcasing Clean Architecture with robust data layer (Dio),
  BLoC/Cubit state management, GoRouter navigation, Material 3 theming,
  localization (en/fa with RTL), caching, shimmer loading, and polished UX.
publish_to: 'none'  # Not published to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"     # Dart SDK range
  flutter: ">=3.22.0"       # Flutter SDK range

dependencies:
  # Flutter SDK & Localization
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.0.0       # Cubit/BLoC
  equatable: ^2.0.5          # Value equality for states/entities

  # Networking
  dio: ^5.7.0                # HTTP client

  # Navigation
  go_router: ^14.2.7         # Declarative routing

  # Dependency Injection
  get_it: ^7.7.0

  # Storage / Caching
  shared_preferences: ^2.2.2  # Simple key-value storage
  cached_network_image: ^3.3.1 # Image caching for flags

  # UI / UX
  shimmer: ^2.0.0            # Skeleton loaders
  flutter_screenutil: ^5.9.0 # Responsive sizing
  cupertino_icons: ^1.0.8

  # Environment Configuration
  flutter_dotenv: ^5.1.0

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^10.0.0         # BLoC/Cubit testing utilities
  mocktail: ^1.0.3           # Mocking library
  http_mock_adapter: ^0.6.1  # Dio request mocking

  # Linting / Static Analysis
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true   # Enable gen_l10n (see l10n.yaml)

  # Asset bundles
  assets:
    - assets/
    - assets/images/
    - .env            # Environment file for flutter_dotenv

  # Custom Fonts
  fonts:
    - family: Kalameh
      fonts:
        - asset: assets/fonts/KalamehFaNum-Thin.ttf
          weight: 300
        - asset: assets/fonts/KalamehFaNum-Regular.ttf
          weight: 400
        - asset: assets/fonts/KalamehFaNum-Bold.ttf
          weight: 700
        - asset: assets/fonts/KalamehFaNum-Black.ttf
          weight: 900